
import { Commissionerate, Station } from './types';

export const POLICE_STATIONS: Station[] = [
  // Hyderabad City
  { id: 'hc-1', name: 'Abids', phone: '040-23231965', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['abids', 'central', 'koti', 'moazzam jahi market'] },
  { id: 'hc-2', name: 'Begumbazar', phone: '040-23458666', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['begum bazar', 'market', 'siddiamber bazar', 'osmangunj'] },
  { id: 'hc-3', name: 'Chikkadpally', phone: '040-23211432', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['chikkadpally', 'rtc x roads', 'narayanguda', 'vst'] },
  { id: 'hc-4', name: 'Musheerabad', phone: '040-27553444', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['musheerabad', 'jail', 'kavadiguda', 'bholakpur'] },
  { id: 'hc-5', name: 'Saifabad', phone: '040-23310566', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['saifabad', 'secretariat', 'lakdikapul', 'adarsnagar'] },
  { id: 'hc-6', name: 'Nampally', phone: '040-23231965', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['nampally', 'railway station', 'mallepally', 'aghapura'] },
  { id: 'hc-7', name: 'Khairatabad', phone: '040-23304866', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['khairatabad', 'rtm', 'raj bhavan road', 'lakdikapul'] },
  { id: 'hc-8', name: 'Gandhi Nagar', phone: '040-23241414', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['gandhi nagar', 'ashok nagar', 'indira park'] },
  { id: 'hc-9', name: 'Domal Guda', phone: '040-24564222', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['domalguda', 'tank bund', 'lower tank bund', 'liberty'] },
  { id: 'hc-10', name: 'Lake Police Station', phone: '040-23231965', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['lake', 'hussain sagar', 'necklace road'] },
  { id: 'hc-11', name: 'Sulthan Bazar', phone: '040-23458666', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['sulthan bazar', 'koti', 'badichowdi'] },
  { id: 'hc-12', name: 'Chaderghat', phone: '040-23458666', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['chaderghat', 'musiriver', 'darulshifa'] },
  { id: 'hc-13', name: 'Afzalgunj', phone: '040-24610808', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['afzalgunj', 'osmania hospital', 'nayapul'] },
  { id: 'hc-14', name: 'Kachiguda', phone: '040-27505666', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['kachiguda', 'railway station', 'nimboliadda'] },
  { id: 'hc-15', name: 'Nallakunta', phone: '040-27008444', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['nallakunta', 'fever hospital', 'shivam road', 'barkatpura'] },
  { id: 'hc-16', name: 'OU City', phone: '040-27018585', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['ou city', 'osmania university', 'tarnaka', 'habsiguda'] },
  { id: 'hc-17', name: 'Malakpet', phone: '040-24511222', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['malakpet', 'race club', 'saleem nagar'] },
  { id: 'hc-18', name: 'Saidabad', phone: '040-24513434', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['saidabad', 'is sadan', 'dharmapuri colony'] },
  { id: 'hc-19', name: 'Amberpet', phone: '040-27038777', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['amberpet', 'dd colony', 'ramanathapur'] },
  { id: 'hc-20', name: 'Banjara Hills', phone: '040-23302828', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['banjara hills', 'road no 1', 'kbr park', 'care hospital'] },
  { id: 'hc-21', name: 'Jubilee Hills', phone: '040-23548989', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['jubilee hills', 'film nagar', 'checkpost', 'road no 36'] },
  { id: 'hc-22', name: 'Panjagutta', phone: '040-23355555', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['panjagutta', 'ameerpet', 'somajiguda', 'erramanzil'] },
  { id: 'hc-23', name: 'SR Nagar', phone: '040-23704646', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['sr nagar', 'sanjeeva reddy nagar', 'erragadda', 'vengal rao nagar'] },
  { id: 'hc-24', name: 'Asifnagar', phone: '040-23732020', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['asifnagar', 'mehdipatnam', 'mallepally'] },
  { id: 'hc-25', name: 'Humayunnagar', phone: '040-24514444', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['humayunnagar', 'mehdipatnam', 'masab tank'] },
  { id: 'hc-26', name: 'Lunger House', phone: '040-23203030', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['lunger house', 'golconda', 'karwan'] },
  { id: 'hc-27', name: 'Shahinayathgunj', phone: '040-23203030', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['shahinayathgunj', 'goshamahal'] },
  { id: 'hc-28', name: 'Habeebnagar', phone: '040-24516666', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['habeebnagar', 'nampally'] },
  { id: 'hc-29', name: 'Kulsumpura', phone: '040-24516666', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['kulsumpura', 'ziaguda', 'puranapul'] },
  { id: 'hc-30', name: 'Charminar', phone: '040-24417777', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['charminar', 'old city', 'laad bazar'] },
  { id: 'hc-31', name: 'Bahadurpura', phone: '040-23521919', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['bahadurpura', 'zoo park', 'tadbun'] },
  { id: 'hc-32', name: 'Kamatipura', phone: '040-23521919', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['kamatipura', 'nagulchinta'] },
  { id: 'hc-33', name: 'Hussaini Alam', phone: '040-24417777', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['hussaini alam', 'moosa bowli'] },
  { id: 'hc-34', name: 'Kalapattar', phone: '040-23521919', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['kalapattar'] },
  { id: 'hc-35', name: 'Mirchowk', phone: '040-23544444', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['mirchowk', 'purani haveli'] },
  { id: 'hc-36', name: 'Dabeerpura', phone: '040-24514444', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['dabeerpura', 'chanchalguda'] },
  { id: 'hc-37', name: 'Moghalpura', phone: '040-24417777', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['moghalpura'] },
  { id: 'hc-38', name: 'Rein Bazar', phone: '040-24417777', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['rein bazar', 'yakutpura'] },
  { id: 'hc-39', name: 'Falaknuma', phone: '040-23544444', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['falaknuma', 'palace', 'vattepally'] },
  { id: 'hc-40', name: 'Chandrayangutta', phone: '040-23544444', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['chandrayangutta', 'barkas', 'pahadi shareef road'] },
  { id: 'hc-41', name: 'Shalibanda', phone: '040-23544444', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['shalibanda'] },
  { id: 'hc-42', name: 'Chatrinaka', phone: '040-23203030', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['chatrinaka', 'uppuguda'] },
  { id: 'hc-43', name: 'Kanchanbagh', phone: '040-24516666', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['kanchanbagh', 'drdl', 'mithani'] },
  { id: 'hc-44', name: 'Bhavani Nagar', phone: '040-24511222', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['bhavani nagar'] },
  { id: 'hc-45', name: 'Madannapet', phone: '040-24511222', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['madannapet', 'kurmaguda'] },
  { id: 'hc-46', name: 'Santoshnagar', phone: '040-24511222', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['santoshnagar', 'champapet'] },
  { id: 'hc-47', name: 'Tolichowki', phone: '040-23548989', commissionerate: Commissionerate.HYDERABAD_CITY, keywords: ['tolichowki', 'seven tombs', 'manikonda road'] },

  // Cyberabad
  { id: 'cb-1', name: 'Chevella', phone: '08413-288333', commissionerate: Commissionerate.CYBERABAD, keywords: ['chevella'] },
  { id: 'cb-2', name: 'Shabad', phone: '08413-288999', commissionerate: Commissionerate.CYBERABAD, keywords: ['shabad'] },
  { id: 'cb-3', name: 'Moinabad', phone: '08414-325555', commissionerate: Commissionerate.CYBERABAD, keywords: ['moinabad'] },
  { id: 'cb-4', name: 'Rajendranagar', phone: '040-24034567', commissionerate: Commissionerate.CYBERABAD, keywords: ['rajendranagar', 'attapur', 'budvel', 'hyderguda'] },
  { id: 'cb-5', name: 'Mailardevpally', phone: '040-24034567', commissionerate: Commissionerate.CYBERABAD, keywords: ['mailardevpally', 'katedan', 'durganagar', 'shastripuram'] },
  { id: 'cb-6', name: 'Attapur', phone: '040-24007777', commissionerate: Commissionerate.CYBERABAD, keywords: ['attapur', 'ring road', 'upperpally'] },
  { id: 'cb-7', name: 'Shankarpally', phone: '08417-288222', commissionerate: Commissionerate.CYBERABAD, keywords: ['shankarpally'] },
  { id: 'cb-8', name: 'Narsingi', phone: '040-23006666', commissionerate: Commissionerate.CYBERABAD, keywords: ['narsingi', 'kokapet', 'puppalguda', 'gandipet'] },
  { id: 'cb-9', name: 'Mokila', phone: '08417-288333', commissionerate: Commissionerate.CYBERABAD, keywords: ['mokila', 'shankarpally road'] },
  { id: 'cb-10', name: 'Madhapur', phone: '040-23167777', commissionerate: Commissionerate.CYBERABAD, keywords: ['madhapur', 'hitech city', 'kavuri hills', 'inorbit'] },
  { id: 'cb-11', name: 'Raidurgam', phone: '040-23167777', commissionerate: Commissionerate.CYBERABAD, keywords: ['raidurgam', 'biodiversity', 'mindspace', 'khajaguda'] },
  { id: 'cb-12', name: 'Gachibowli', phone: '040-23006666', commissionerate: Commissionerate.CYBERABAD, keywords: ['gachibowli', 'financial district', 'nanakramguda', 'dlf'] },
  { id: 'cb-13', name: 'Chandanagar', phone: '040-23017777', commissionerate: Commissionerate.CYBERABAD, keywords: ['chandanagar', 'lingampally', 'bhel'] },
  { id: 'cb-14', name: 'Miyapur', phone: '040-23037777', commissionerate: Commissionerate.CYBERABAD, keywords: ['miyapur', 'allwyn x roads', 'hydernagar'] },
  { id: 'cb-15', name: 'RC Puram', phone: '08414-247777', commissionerate: Commissionerate.CYBERABAD, keywords: ['rc puram', 'ramachandrapuram', 'bhel'] },
  { id: 'cb-16', name: 'Kolluru', phone: '08414-247777', commissionerate: Commissionerate.CYBERABAD, keywords: ['kolluru', 'tellapur'] },
  { id: 'cb-17', name: 'Balanagar', phone: '040-23707777', commissionerate: Commissionerate.CYBERABAD, keywords: ['balanagar', 'hal'] },
  { id: 'cb-18', name: 'Sanathnagar', phone: '040-23718888', commissionerate: Commissionerate.CYBERABAD, keywords: ['sanathnagar', 'fatehnagar', 'moosapet'] },
  { id: 'cb-19', name: 'Jeedimetla', phone: '040-23048888', commissionerate: Commissionerate.CYBERABAD, keywords: ['jeedimetla', 'industries'] },
  { id: 'cb-20', name: 'Jagadgirigutta', phone: '040-23048888', commissionerate: Commissionerate.CYBERABAD, keywords: ['jagadgirigutta'] },
  { id: 'cb-21', name: 'Kukatpally', phone: '040-23167777', commissionerate: Commissionerate.CYBERABAD, keywords: ['kukatpally', 'jntu', 'moosapet'] },
  { id: 'cb-22', name: 'KPHB Colony', phone: '040-23167777', commissionerate: Commissionerate.CYBERABAD, keywords: ['kphb', 'kukatpally housing board'] },
  { id: 'cb-23', name: 'Bachupally', phone: '08418-247777', commissionerate: Commissionerate.CYBERABAD, keywords: ['bachupally', 'vnr vignana jyothi'] },
  { id: 'cb-24', name: 'Allapur', phone: '08418-247777', commissionerate: Commissionerate.CYBERABAD, keywords: ['allapur', 'borabanda'] },
  { id: 'cb-25', name: 'Medchal', phone: '08418-247777', commissionerate: Commissionerate.CYBERABAD, keywords: ['medchal'] },
  { id: 'cb-26', name: 'Dundigal', phone: '08418-247777', commissionerate: Commissionerate.CYBERABAD, keywords: ['dundigal'] },
  { id: 'cb-27', name: 'Suraram', phone: '08418-247777', commissionerate: Commissionerate.CYBERABAD, keywords: ['suraram'] },
  { id: 'cb-28', name: 'Pet Basheerabad', phone: '08418-247777', commissionerate: Commissionerate.CYBERABAD, keywords: ['pet basheerabad'] },
  { id: 'cb-29', name: 'Shamirpet', phone: '08418-247777', commissionerate: Commissionerate.CYBERABAD, keywords: ['shamirpet'] },
  { id: 'cb-30', name: 'Alwal', phone: '040-23048888', commissionerate: Commissionerate.CYBERABAD, keywords: ['alwal', 'bolarum', 'venkatapuram'] },
  { id: 'cb-31', name: 'Genome Valley', phone: '08418-247777', commissionerate: Commissionerate.CYBERABAD, keywords: ['genome valley', 'turkapally'] },

  // Rachakonda
  { id: 'rk-1', name: 'Malkajgiri', phone: '040-27854080', commissionerate: Commissionerate.RACHAKONDA, keywords: ['malkajgiri', 'vinayak nagar'] },
  { id: 'rk-2', name: 'Nacharam', phone: '040-27854080', commissionerate: Commissionerate.RACHAKONDA, keywords: ['nacharam', 'habsiguda', 'malla reddy nagar'] },
  { id: 'rk-3', name: 'Uppal', phone: '040-27854080', commissionerate: Commissionerate.RACHAKONDA, keywords: ['uppal', 'stadium', 'boduppal'] },
  { id: 'rk-4', name: 'Medipally', phone: '040-27853834', commissionerate: Commissionerate.RACHAKONDA, keywords: ['medipally', 'warangal highway'] },
  { id: 'rk-5', name: 'Ghatkesar', phone: '040-27853969', commissionerate: Commissionerate.RACHAKONDA, keywords: ['ghatkesar'] },
  { id: 'rk-6', name: 'Pocharam IT Corridor', phone: '040-27853969', commissionerate: Commissionerate.RACHAKONDA, keywords: ['pocharam', 'infosys'] },
  { id: 'rk-7', name: 'Kushaiguda', phone: '040-27854080', commissionerate: Commissionerate.RACHAKONDA, keywords: ['kushaiguda', 'ecil', 'moula ali'] },
  { id: 'rk-8', name: 'Cherlapally', phone: '040-27854080', commissionerate: Commissionerate.RACHAKONDA, keywords: ['cherlapally', 'jail'] },
  { id: 'rk-9', name: 'Neredmet', phone: '040-27854080', commissionerate: Commissionerate.RACHAKONDA, keywords: ['neredmet', 'sainikpuri', 'rk puram'] },
  { id: 'rk-10', name: 'Jawahar Nagar', phone: '040-27854080', commissionerate: Commissionerate.RACHAKONDA, keywords: ['jawahar nagar', 'kapra'] },
  { id: 'rk-11', name: 'Keesara', phone: '040-27854080', commissionerate: Commissionerate.RACHAKONDA, keywords: ['keesara'] },
  { id: 'rk-12', name: 'LB Nagar', phone: '040-27853819', secondaryPhone: '8712662003', commissionerate: Commissionerate.RACHAKONDA, keywords: ['lb nagar', 'lal bahadur nagar', 'kamineni'] },
  { id: 'rk-13', name: 'Saroornagar', phone: '040-27853819', commissionerate: Commissionerate.RACHAKONDA, keywords: ['saroornagar', 'rk puram', 'kothapet'] },
  { id: 'rk-14', name: 'Chaitanyapuri', phone: '040-27853819', commissionerate: Commissionerate.RACHAKONDA, keywords: ['chaitanyapuri', 'dilshuknagar'] },
  { id: 'rk-15', name: 'Nagole', phone: '040-27853819', commissionerate: Commissionerate.RACHAKONDA, keywords: ['nagole', 'uppal road'] },
  { id: 'rk-16', name: 'Vanasthalipuram', phone: '040-27853819', commissionerate: Commissionerate.RACHAKONDA, keywords: ['vanasthalipuram', 'hayathnagar', 'panama'] },
  { id: 'rk-17', name: 'Hayathnagar', phone: '040-27853819', commissionerate: Commissionerate.RACHAKONDA, keywords: ['hayathnagar', 'lumbini park'] },
  { id: 'rk-18', name: 'Meerpet', phone: '040-27853900', commissionerate: Commissionerate.RACHAKONDA, keywords: ['meerpet', 'jillelguda'] },
  { id: 'rk-19', name: 'Abdullapurmet', phone: '040-27853900', commissionerate: Commissionerate.RACHAKONDA, keywords: ['abdullapurmet'] },
  { id: 'rk-20', name: 'Ibrahimpatnam', phone: '040-27853900', commissionerate: Commissionerate.RACHAKONDA, keywords: ['ibrahimpatnam'] },
  { id: 'rk-21', name: 'Manchal', phone: '8712662004', commissionerate: Commissionerate.RACHAKONDA, keywords: ['manchal'] },
  { id: 'rk-22', name: 'Yacharam', phone: '8712662004', commissionerate: Commissionerate.RACHAKONDA, keywords: ['yacharam'] },
  { id: 'rk-23', name: 'Kandukur', phone: '8712662004', commissionerate: Commissionerate.RACHAKONDA, keywords: ['kandukur'] },
  { id: 'rk-24', name: 'Maheshwaram', phone: '8712662004', commissionerate: Commissionerate.RACHAKONDA, keywords: ['maheshwaram'] },
  { id: 'rk-25', name: 'Adibatla', phone: '8712662004', commissionerate: Commissionerate.RACHAKONDA, keywords: ['adibatla', 'tcs'] },
  { id: 'rk-26', name: 'Madgul', phone: '8712662004', commissionerate: Commissionerate.RACHAKONDA, keywords: ['madgul'] },
  { id: 'rk-27', name: 'Choutuppal', phone: '08685-295202', secondaryPhone: '8712662005', commissionerate: Commissionerate.RACHAKONDA, keywords: ['choutuppal'] },
  { id: 'rk-28', name: 'Pochampally', phone: '08685-295202', commissionerate: Commissionerate.RACHAKONDA, keywords: ['pochampally'] },

  // Women PS
  { id: 'w-1', name: 'CCS Women', phone: '040-27852355', secondaryPhone: '8712660998', commissionerate: Commissionerate.WOMEN_PS, keywords: ['women', 'ccs'] },
  { id: 'w-2', name: 'Begumpet Women', phone: '9490616437', commissionerate: Commissionerate.WOMEN_PS, keywords: ['women', 'begumpet'] },
  { id: 'w-3', name: 'South Zone Women', phone: '8712660301', commissionerate: Commissionerate.WOMEN_PS, keywords: ['women', 'south zone'] },
  { id: 'w-4', name: 'Cyberabad Women (Madhapur)', phone: '040-23167777', commissionerate: Commissionerate.WOMEN_PS, keywords: ['women', 'cyberabad', 'madhapur'] },
  { id: 'w-5', name: 'Uppal Women', phone: '040-27854080', commissionerate: Commissionerate.WOMEN_PS, keywords: ['women', 'uppal'] },
  { id: 'w-6', name: 'LB Nagar Women', phone: '040-27853819', commissionerate: Commissionerate.WOMEN_PS, keywords: ['women', 'lb nagar'] },

  // Bharosa
  { id: 'b-1', name: 'Hyderabad Bharosa (Saifabad)', phone: '1098', secondaryPhone: '100', commissionerate: Commissionerate.BHAROSA, keywords: ['bharosa', 'hyderabad'] },
  { id: 'b-2', name: 'Rachakonda Bharosa (Medipally)', phone: '8712662013', commissionerate: Commissionerate.BHAROSA, keywords: ['bharosa', 'rachakonda'] },
];
